### ISSUE TITLE
Translate converting_to_string.rs

### ISSUE THREAD

**Issue by clarus** [formal-land/coq-of-rust#30]
Translate the file https://github.com/formal-land/coq-of-rust/blob/main/examples-from-rust-book/conversion/converting_to_string.rs

**Comment by InfiniteEchoes** [comment]
## Potential Module Naming Conflict with Coq

Some of the example requires using some rust modules. For example in `converting_to_string.rs`:

```rust
use std::fmt;
```

And it will generate the following Coq line:

```
Module fmt := std.fmt.
```

The translation is supposed to refer to another(?) translated module from Rust code. However, this line actually defines a Coq module `fmt` as an alias for Coq standard module `fmt`.  This will cause potentially all the followed content in the file actually use the proof from Coq's `fmt` rather than some `fmt` of Rust. While in `converting_to_string.v` the translation doesn't cause any issue, this issue manifest as an error in `conversion/from.v`:

```
File ".\conversion\from.v", line 6, characters 15-31:
Error: "std.convert.From" is not a module.
```

In `top_level.rs` currently, a module being presented as a `ItemKind::Mod` HIR Object will be directly parsed as a `TopLevelItem::Module` object. It's `name` seems to be the lhs of the generated Coq code, and its `body` seems to be the rhs. I don't know what will the `TopLevelItem` object be passed to to generate the final Coq code string.

## Personal Suggestions
For now I see this problem as something that could actually prevent to see more difficult problems in the depth. For a quick fix, we can make the generator comment out the library references, or otherwise we just provide a blank line. For some solid fix though, we'll have to design a std library for Rust-translated Coq code.

--------

# Error Messages

Below is the output error for current files being listed in the issues. Note that `dead_code.v` should be totally safe as it doesn't require any libraries.

## /conversion/converting_to_string.v

```
The following term contains unresolved implicit arguments:
  (fun (self : ref Self) (f : mut_ref fmt.Formatter) =>
   method _ f
     (_crate.fmt.ImplArguments.new_v1 ["Circle of radius "]
        [_crate.fmt.ImplArgumentV1.new_display (NamedField.get self)]))
More precisely: 
- ?T: Cannot infer the implicit parameter T of _crate.fmt.ImplArgumentV1.new_display whose
  type is "Set" in environment:
  self : ref Self
  f : mut_ref fmt.Formatter
- ?H: Cannot infer the implicit parameter H of _crate.fmt.ImplArgumentV1.new_display whose
  type is "_crate.fmt.Display.Class ?T" (no type class instance found) in
  environment:
  self : ref Self
  f : mut_ref fmt.Formatter
- ?Class: Cannot infer the implicit parameter Class of NamedField.get whose type is
  "NamedField.Class (ref Self) "radius" (ref ?T)" (no type class instance found) in
  environment:
  self : ref Self
  f : mut_ref fmt.Formatter 
```

## .\conversion\from.v

```
File ".\conversion\from.v", line 6, characters 15-31:
Error: "std.convert.From" is not a module.
```

## ./conversion/into.v

```
File "./conversion/into.v", line 6, characters 15-31:
Error: "std.convert.From" is not a module.
```

## ./conversion/parsing_a_string.v 

```
File "./conversion/parsing_a_string.v", line 9, characters 13-16:
Error: The reference add was not found in the current environment.
```

## ./conversion/try_from_and_try_into.v

```
File "./conversion/try_from_and_try_into.v", line 6, characters 18-37:
Error: "std.convert.TryFrom" is not a module.
```

**Comment by clarus** [comment]
OK top for all the comments!
