### ISSUE TITLE
attempted to read from stolen value: rustc_middle::thir::Thir

### ISSUE THREAD

**Issue by jmikedupont2** [formal-land/coq-of-rust#453]
I have an example here that crashes the compiler
https://github.com/meta-introspector/json/pull/1

thread 'rustc' panicked at lib/src/expression.rs:710:21:                           attempted to read from stolen value: rustc_middle::thir::Thir
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: `serde_json` (lib) generated 143 warnings                                 error: could not compile `serde_json`

**Comment by clarus** [comment]
Hello, OK, thanks for the report! Yes this bug is very annoying, I was investigating it the other day, I don't know if there is a real fix or this is a limitation of the Rust API. We should at least have a wrapper around this error, I will make a pull request for that. On Jan 28, 2024 21:54, Mike DuPont ***@***.***> wrote:
I have an example here that crashes the compiler
meta-introspector/json#1
thread 'rustc' panicked at lib/src/expression.rs:710:21:                           attempted to read from stolen value: rustc_middle::thir::Thir
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: serde_json (lib) generated 143 warnings                                 error: could not compile serde_json

**Comment by jmikedupont2** [comment]
i will be happy to report that I created a patch to remove this error by returning a bogus value and it worked for me.https://github.com/formal-land/coq-of-rust/pull/454
